import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { getRecordsIncludingDeleted } from "@/lib/db";
import { type RecordFilters, filterRecords } from "@/lib/search";
import { getBilingualSpeciesName } from "@/lib/terminology";
type SearchParams = Record<string, string | string[] | undefined>;
const readParam = (params: SearchParams, name: string) => { const value = params[name]; return Array.isArray(value) ? value[0] ?? "" : value ?? ""; };
export default async function AdminRecordsPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  await requireAdmin();
  const params = await searchParams;
  const filters: RecordFilters = { keyword: readParam(params, "keyword"), sourceCategory: readParam(params, "sourceCategory"), activityCategory: readParam(params, "activityCategory"), evidenceLevel: readParam(params, "evidenceLevel"), structureCompleteness: readParam(params, "structureCompleteness"), reviewStatus: readParam(params, "reviewStatus"), yearFrom: Number(readParam(params, "yearFrom")) || undefined, yearTo: Number(readParam(params, "yearTo")) || undefined };
  const activeRecords = (await getRecordsIncludingDeleted()).filter((record) => !record.deleted_at);
  const filteredRecords = filterRecords(activeRecords, filters);
  return <><div className="admin-page-heading"><div><p className="eyebrow">记录管理</p><h1>数据记录</h1></div><Link className="button button--primary" href="/admin/records/new">新建记录</Link></div><form className="admin-search" method="get"><label className="filter-field filter-field--wide"><span>关键词</span><input defaultValue={filters.keyword} name="keyword" placeholder="名称、物种、DOI、作用机制..." /></label><label className="filter-field"><span>来源类别</span><input defaultValue={filters.sourceCategory} name="sourceCategory" /></label><label className="filter-field"><span>活性类别</span><input defaultValue={filters.activityCategory} name="activityCategory" /></label><label className="filter-field"><span>证据等级</span><input defaultValue={filters.evidenceLevel} name="evidenceLevel" /></label><label className="filter-field"><span>结构完整度</span><input defaultValue={filters.structureCompleteness} name="structureCompleteness" /></label><label className="filter-field"><span>审核状态</span><input defaultValue={filters.reviewStatus} name="reviewStatus" /></label><label className="filter-field"><span>起始年份</span><input defaultValue={filters.yearFrom} name="yearFrom" type="number" /></label><label className="filter-field"><span>截止年份</span><input defaultValue={filters.yearTo} name="yearTo" type="number" /></label><button className="button button--quiet" type="submit">筛选记录</button></form><p className="section-note">当前筛选条件匹配 {filteredRecords.length} 条记录。</p><div className="table-wrap"><table className="record-table"><thead><tr><th>标准名称</th><th>英文名称</th><th>来源物种</th><th>年份</th><th>审核状态</th><th><span className="sr-only">编辑记录</span></th></tr></thead><tbody>{filteredRecords.map((record) => <tr key={record.id}><td className="record-table__primary">{record.standard_name || "未记录"}</td><td>{record.english_name || "未记录"}</td><td title={record.source_species}>{getBilingualSpeciesName(record.source_species)}</td><td>{record.publication_year ?? "-"}</td><td>{record.review_status}</td><td><Link className="text-link" href={`/admin/records/${record.id}/edit`}>编辑</Link></td></tr>)}</tbody></table></div></>;
}
