import Link from "next/link";
import { getRecords } from "@/lib/db";
import { type RecordFilters, filterRecords } from "@/lib/search";
type SearchParams = Record<string, string | string[] | undefined>;
const readParam = (params: SearchParams, name: string) => { const value = params[name]; return Array.isArray(value) ? value[0] ?? "" : value ?? ""; };
export default async function AdminRecordsPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams;
  const filters: RecordFilters = { keyword: readParam(params, "keyword"), sourceCategory: readParam(params, "sourceCategory"), activityCategory: readParam(params, "activityCategory"), evidenceLevel: readParam(params, "evidenceLevel"), structureCompleteness: readParam(params, "structureCompleteness"), reviewStatus: readParam(params, "reviewStatus"), yearFrom: Number(readParam(params, "yearFrom")) || undefined, yearTo: Number(readParam(params, "yearTo")) || undefined };
  const filteredRecords = filterRecords(await getRecords(), filters);
  return <><div className="admin-page-heading"><div><p className="eyebrow">Record management</p><h1>Records</h1></div><Link className="button button--primary" href="/admin/records/new">New record</Link></div><form className="admin-search" method="get"><label className="filter-field filter-field--wide"><span>Keyword</span><input defaultValue={filters.keyword} name="keyword" placeholder="Name, species, DOI, mechanism..." /></label><label className="filter-field"><span>Source category</span><input defaultValue={filters.sourceCategory} name="sourceCategory" /></label><label className="filter-field"><span>Activity category</span><input defaultValue={filters.activityCategory} name="activityCategory" /></label><label className="filter-field"><span>Evidence level</span><input defaultValue={filters.evidenceLevel} name="evidenceLevel" /></label><label className="filter-field"><span>Structure completeness</span><input defaultValue={filters.structureCompleteness} name="structureCompleteness" /></label><label className="filter-field"><span>Review status</span><input defaultValue={filters.reviewStatus} name="reviewStatus" /></label><label className="filter-field"><span>Year from</span><input defaultValue={filters.yearFrom} name="yearFrom" type="number" /></label><label className="filter-field"><span>Year to</span><input defaultValue={filters.yearTo} name="yearTo" type="number" /></label><button className="button button--quiet" type="submit">Filter records</button></form><p className="section-note">{filteredRecords.length} records match the current filters.</p><div className="table-wrap"><table className="record-table"><thead><tr><th>Standard name</th><th>English name</th><th>Source species</th><th>Year</th><th>Review</th><th><span className="sr-only">Edit record</span></th></tr></thead><tbody>{filteredRecords.map((record) => <tr key={record.id}><td className="record-table__primary">{record.standard_name || "Not recorded"}</td><td>{record.english_name || "Not recorded"}</td><td>{record.source_species || "Not recorded"}</td><td>{record.publication_year ?? "-"}</td><td>{record.review_status}</td><td><Link className="text-link" href={`/admin/records/${record.id}/edit`}>Edit</Link></td></tr>)}</tbody></table></div></>;
}
