import { randomUUID } from "node:crypto";
import { resolveDatabaseBackend } from "./db";
import { getPostgresPool } from "./postgres";
import { getDatabase } from "./sqlite";
import type { AttachmentStore } from "./cos-store";
import { AttachmentError, MAX_ATTACHMENT_BYTES } from "./attachments";
import { enqueueCosCleanup } from "./cos-cleanup";

export type Attachment = { id:string; recordId:string; objectKey:string; originalFilename:string; mimeType:string; byteSize:number; description:string; isPublic:boolean; rightsConfirmedAt:string; createdAt:string; deletedAt:string|null };
type CreateInput={recordId:string;objectKey:string;originalFilename:string;mimeType:string;byteSize:number;description:string;isPublic:boolean;actor:string};
const map=(r:Record<string,unknown>):Attachment=>({id:String(r.id),recordId:String(r.record_id),objectKey:String(r.object_key),originalFilename:String(r.original_filename),mimeType:String(r.mime_type),byteSize:Number(r.byte_size),description:String(r.description),isPublic:Boolean(r.is_public),rightsConfirmedAt:new Date(String(r.rights_confirmed_at)).toISOString(),createdAt:new Date(String(r.created_at)).toISOString(),deletedAt:r.deleted_at?new Date(String(r.deleted_at)).toISOString():null});

function nextSlot(rows:{slot_number:number}[]) { for(let i=1;i<=10;i++) if(!rows.some(r=>Number(r.slot_number)===i)) return i; throw new AttachmentError("每条记录最多上传 10 个附件"); }

async function createPg(input:CreateInput) {
  const client=await getPostgresPool().connect(); const id=randomUUID();
  try { await client.query("BEGIN"); const record=await client.query("SELECT id FROM polysaccharide_records WHERE id=$1 AND deleted_at IS NULL FOR UPDATE",[input.recordId]);if(!record.rowCount)throw new AttachmentError("记录不存在或已删除");
    const slots=await client.query("SELECT slot_number FROM record_attachments WHERE record_id=$1 AND deleted_at IS NULL FOR UPDATE",[input.recordId]); const slot=nextSlot(slots.rows as {slot_number:number}[]);
    const result=await client.query("INSERT INTO record_attachments(id,record_id,object_key,original_filename,mime_type,byte_size,description,is_public,rights_confirmed_at,created_by,slot_number,upload_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CURRENT_TIMESTAMP,$9,$10,'ready') RETURNING *",[id,input.recordId,input.objectKey,input.originalFilename,input.mimeType,input.byteSize,input.description,input.isPublic,input.actor,slot]);
    await client.query("INSERT INTO audit_logs(id,actor_type,actor_id,action,entity_type,entity_id,changed_fields) VALUES($1,'admin',$2,'attachment_upload','record_attachment',$3,$4)",[randomUUID(),input.actor,id,{record_id:input.recordId,mime_type:input.mimeType,byte_size:input.byteSize}]); await client.query("COMMIT"); return map(result.rows[0]);
  } catch(e){await client.query("ROLLBACK");throw e;} finally{client.release();}
}

function createSqlite(input:CreateInput) { const db=getDatabase(); return db.transaction(()=>{const record=db.prepare("SELECT id FROM polysaccharide_records WHERE id=? AND deleted_at IS NULL").get(input.recordId);if(!record)throw new AttachmentError("记录不存在或已删除");const slots=db.prepare("SELECT slot_number FROM record_attachments WHERE record_id=? AND deleted_at IS NULL").all(input.recordId) as {slot_number:number}[];const slot=nextSlot(slots);const id=randomUUID(),now=new Date().toISOString();db.prepare("INSERT INTO record_attachments VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,input.recordId,input.objectKey,input.originalFilename,input.mimeType,input.byteSize,input.description,input.isPublic?1:0,now,input.actor,now,null,null,slot,"ready");db.prepare("INSERT INTO audit_logs(id,actor_type,actor_id,action,entity_type,entity_id,changed_fields,created_at) VALUES(?,'admin',?,'attachment_upload','record_attachment',?,?,?)").run(randomUUID(),input.actor,id,JSON.stringify({record_id:input.recordId,mime_type:input.mimeType,byte_size:input.byteSize}),now);return map(db.prepare("SELECT * FROM record_attachments WHERE id=?").get(id) as Record<string,unknown>);}).immediate(); }

export async function persistUploadedAttachment(input:CreateInput, store:AttachmentStore, bytes:Buffer) { await store.put(input.objectKey,bytes,input.mimeType);try{return resolveDatabaseBackend()==="postgres"?await createPg(input):createSqlite(input);}catch(error){try{await store.remove(input.objectKey);}catch(cleanupError){await enqueueCosCleanup(input.objectKey,cleanupError);throw new AttachmentError("附件元数据保存失败，COS 补偿删除已进入重试队列");}throw error;} }

export async function listRecordAttachments(recordId:string, admin=false) { const where=admin?"a.record_id=$1 AND a.deleted_at IS NULL":"a.record_id=$1 AND a.deleted_at IS NULL AND a.is_public=TRUE AND a.rights_confirmed_at IS NOT NULL AND a.upload_status='ready' AND r.deleted_at IS NULL";if(resolveDatabaseBackend()==="postgres"){const q=await getPostgresPool().query(`SELECT a.* FROM record_attachments a JOIN polysaccharide_records r ON r.id=a.record_id WHERE ${where} ORDER BY a.created_at`,[recordId]);return q.rows.map(map);}const rows=getDatabase().prepare(`SELECT a.* FROM record_attachments a JOIN polysaccharide_records r ON r.id=a.record_id WHERE ${where.replaceAll("$1","?").replace("TRUE","1")} ORDER BY a.created_at`).all(recordId) as Record<string,unknown>[];return rows.map(map); }

export async function getPublicAttachment(id:string) { const sql="SELECT a.* FROM record_attachments a JOIN polysaccharide_records r ON r.id=a.record_id WHERE a.id=$1 AND a.is_public=TRUE AND a.rights_confirmed_at IS NOT NULL AND a.upload_status='ready' AND a.deleted_at IS NULL AND r.deleted_at IS NULL";if(resolveDatabaseBackend()==="postgres"){const r=await getPostgresPool().query(sql,[id]);return r.rowCount?map(r.rows[0]):null;}const row=getDatabase().prepare(sql.replaceAll("$1","?").replace("TRUE","1")).get(id) as Record<string,unknown>|undefined;return row?map(row):null; }

async function authorizePublicAttachment(id:string){return getPublicAttachment(id);}
export async function readAuthorizedAttachment(id:string,store:AttachmentStore){const first=await authorizePublicAttachment(id);if(!first)return null;const opened=await store.open(first.objectKey,{maxBytes:MAX_ATTACHMENT_BYTES,timeoutMs:30_000});const latest=await authorizePublicAttachment(id);if(!latest||latest.objectKey!==first.objectKey){opened.stream.destroy();return null;}return{attachment:latest,stream:opened.stream,size:opened.size};}

export async function updateAttachment(id:string,actor:string,description:string,isPublic:boolean,deleted=false){if(description.trim().length>500)throw new AttachmentError("附件说明不得超过 500 个字符");const now=new Date().toISOString();if(resolveDatabaseBackend()==="postgres"){const c=await getPostgresPool().connect();try{await c.query("BEGIN");const r=await c.query("UPDATE record_attachments SET description=$1,is_public=$2,deleted_at=CASE WHEN $3 THEN CURRENT_TIMESTAMP ELSE deleted_at END,deleted_by=CASE WHEN $3 THEN $4 ELSE deleted_by END WHERE id=$5 AND deleted_at IS NULL RETURNING *",[description.trim(),isPublic,deleted,actor,id]);if(!r.rowCount)throw new AttachmentError("附件不存在或已删除");await c.query("INSERT INTO audit_logs(id,actor_type,actor_id,action,entity_type,entity_id,changed_fields) VALUES($1,'admin',$2,$3,'record_attachment',$4,$5)",[randomUUID(),actor,deleted?"attachment_delete":"attachment_update",id,{description:description.trim(),is_public:isPublic}]);await c.query("COMMIT");return map(r.rows[0]);}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}return getDatabase().transaction(()=>{const row=getDatabase().prepare("SELECT * FROM record_attachments WHERE id=? AND deleted_at IS NULL").get(id);if(!row)throw new AttachmentError("附件不存在或已删除");getDatabase().prepare("UPDATE record_attachments SET description=?,is_public=?,deleted_at=CASE WHEN ? THEN ? ELSE deleted_at END,deleted_by=CASE WHEN ? THEN ? ELSE deleted_by END WHERE id=?").run(description.trim(),isPublic?1:0,deleted?1:0,now,deleted?1:0,actor,id);getDatabase().prepare("INSERT INTO audit_logs VALUES(?,'admin',?,?, 'record_attachment',?,?,?)").run(randomUUID(),actor,deleted?"attachment_delete":"attachment_update",id,JSON.stringify({description:description.trim(),is_public:isPublic}),now);return true;}).immediate();}
