import { randomUUID } from "node:crypto";
import { resolveDatabaseBackend } from "./db";
import { getPostgresPool } from "./postgres";
import { getDatabase } from "./sqlite";
import type { AttachmentStore } from "./cos-store";
const MAX_ATTEMPTS=5,LEASE_MS=5*60_000;
const errorText=(e:unknown)=>(e instanceof Error?e.message:String(e)).slice(0,1000);

export async function enqueueCosCleanup(objectKey:string,error:unknown){const id=randomUUID(),now=new Date().toISOString(),message=errorText(error);if(resolveDatabaseBackend()==="postgres"){await getPostgresPool().query("INSERT INTO cos_cleanup_jobs(id,object_key,last_error) VALUES($1,$2,$3) ON CONFLICT(object_key) DO UPDATE SET status='pending',last_error=EXCLUDED.last_error,next_attempt_at=CURRENT_TIMESTAMP,locked_until=NULL,updated_at=CURRENT_TIMESTAMP",[id,objectKey,message]);return;}getDatabase().prepare("INSERT INTO cos_cleanup_jobs(id,object_key,status,attempt_count,last_error,next_attempt_at,locked_until,alert_required,created_at,updated_at) VALUES(?,?,'pending',0,?,?,NULL,0,?,?) ON CONFLICT(object_key) DO UPDATE SET status='pending',last_error=excluded.last_error,next_attempt_at=excluded.next_attempt_at,locked_until=NULL,updated_at=excluded.updated_at").run(id,objectKey,message,now,now,now);}

async function claim(limit:number){const now=new Date(),lease=new Date(now.getTime()+LEASE_MS);if(resolveDatabaseBackend()==="postgres"){const c=await getPostgresPool().connect();try{await c.query("BEGIN");const result=await c.query(`WITH due AS (SELECT id FROM cos_cleanup_jobs WHERE (status='pending' AND next_attempt_at<=CURRENT_TIMESTAMP) OR (status='processing' AND locked_until<=CURRENT_TIMESTAMP) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT $1) UPDATE cos_cleanup_jobs j SET status='processing',locked_until=$2,updated_at=CURRENT_TIMESTAMP FROM due WHERE j.id=due.id RETURNING j.*`,[limit,lease.toISOString()]);await c.query("COMMIT");return result.rows;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
  const db=getDatabase();return db.transaction(()=>{const rows=db.prepare("SELECT * FROM cos_cleanup_jobs WHERE (status='pending' AND next_attempt_at<=?) OR (status='processing' AND locked_until<=?) ORDER BY created_at LIMIT ?").all(now.toISOString(),now.toISOString(),limit) as Record<string,unknown>[];const update=db.prepare("UPDATE cos_cleanup_jobs SET status='processing',locked_until=?,updated_at=? WHERE id=?");for(const row of rows)update.run(lease.toISOString(),now.toISOString(),row.id);return rows.map(row=>({...row,status:"processing",locked_until:lease.toISOString()}));}).immediate();
}

export async function processCosCleanupJobs(store:AttachmentStore,limit=20){const jobs=await claim(limit);let completed=0,failed=0;for(const job of jobs){const id=String(job.id),key=String(job.object_key),attempt=Number(job.attempt_count)+1;try{await store.remove(key);await finish(id,key,attempt,true,null);completed++;}catch(e){await finish(id,key,attempt,false,errorText(e));failed++;}}return{processed:jobs.length,completed,failed};}

async function finish(id:string,key:string,attempt:number,success:boolean,message:string|null){const terminal=!success&&attempt>=MAX_ATTEMPTS,status=success?"completed":terminal?"failed":"pending",action=success?"attachment_cleanup_success":"attachment_cleanup_failed",next=new Date(Date.now()+Math.min(60,2**attempt)*60_000).toISOString();if(resolveDatabaseBackend()==="postgres"){const c=await getPostgresPool().connect();try{await c.query("BEGIN");await c.query("UPDATE cos_cleanup_jobs SET status=$1,attempt_count=$2,last_error=$3,next_attempt_at=$4,locked_until=NULL,alert_required=$5,updated_at=CURRENT_TIMESTAMP,completed_at=CASE WHEN $1='completed' THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=$6 AND status='processing'",[status,attempt,message,next,terminal,id]);await c.query("INSERT INTO audit_logs(id,actor_type,actor_id,action,entity_type,entity_id,changed_fields) VALUES($1,'system','cos-cleanup',$2,'cos_cleanup_job',$3,$4)",[randomUUID(),action,id,{object_key:key,attempt,status,alert_required:terminal}]);await c.query("COMMIT");}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}return;}const db=getDatabase();db.transaction(()=>{const now=new Date().toISOString();db.prepare("UPDATE cos_cleanup_jobs SET status=?,attempt_count=?,last_error=?,next_attempt_at=?,locked_until=NULL,alert_required=?,updated_at=?,completed_at=CASE WHEN ?='completed' THEN ? ELSE NULL END WHERE id=? AND status='processing'").run(status,attempt,message,next,terminal?1:0,now,status,now,id);db.prepare("INSERT INTO audit_logs VALUES(?,'system','cos-cleanup',?,'cos_cleanup_job',?,?,?)").run(randomUUID(),action,id,JSON.stringify({object_key:key,attempt,status,alert_required:terminal}),now);}).immediate();}
